# Generated by Django 3.2.15 on 2022-08-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_user_first_name'),
        ('reviews', '0004_auto_20220827_0022'),
    ]

    operations = [
    ]
